# Generated by Django 5.2.8 on 2026-05-16 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Friends',
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['created_at'], 'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterModelTable(
            name='friends',
            table='Friends',
        ),
    ]
