# Generated by Django 5.2.8 on 2026-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_rename_connections_friends_alter_friends_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversations',
            options={'ordering': ['created_at'], 'verbose_name': 'conversation', 'verbose_name_plural': 'conversations'},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['created_at'], 'verbose_name': 'friend', 'verbose_name_plural': 'friends'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['date_sent'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelTable(
            name='conversations',
            table='conversations',
        ),
        migrations.AlterModelTable(
            name='friends',
            table='friends',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
    ]
